export enum CodeStatus {
  GLOBAL_SUCCESS = 0,
  GLOBAL_SYSTEM_ERROR = -1,

  AWS_INVALID_UPLOAD_MODE = 501,
  AWS_INVALID_RESOURCE_TYPE = 502,
  AWS_NO_TARGET_ID = 503,
  AWS_TOO_MANY_FILES = 504,

  USER_NOT_EXIST = 601,

  DRINK_BOTTLE_NOT_EXIST = 701,
}
